### ISSUE TITLE
Asiakas pystyy lisäämään järjestelmään article-tyyppisen viitteen

### ISSUE THREAD

**Issue by t0ffe** [t0ffe/OhTu-miniprojekti#1]
TODO:

- [x] #5
    - [x] #6
- [x] #7
- [x] #8

**Comment by t0ffe** [comment]
Selvitetään mitä kaikkia kenttiä pitää olla. Mitkä ovat pakollisia ja mitä vapaaehtoisia.

**Comment by emmi-ko** [comment]
lomake done
