### ISSUE TITLE
GHA Robot -testit eivät mene läpi

### ISSUE THREAD

**Issue by candyliaa** [t0ffe/OhTu-miniprojekti#4]
Tiedostot app.py, db_helper.py ja todo_repository.py käyttävät nyt tietokannan taulua articles, jota varten html-tiedostoja tulisi muuttaa. Robot testit tulee myös kirjoittaa uudelleen sopivaksi.

**Comment by emmi-ko** [comment]
Robot-testit lisätty ja menevät läpi.
