### ISSUE TITLE
funktio millä tietokantaan saa lisättyä tietoa

### ISSUE THREAD

**Issue by t0ffe** [t0ffe/OhTu-miniprojekti#7]
[Vaadittavat kentät](https://github.com/t0ffe/OhTu-miniprojekti/issues/5)

- [x] funktio
- [x] sille testit

**Comment by McIlola** [comment]
Funktio lisätty, ei testattu.

**Comment by McIlola** [comment]
Funktio lisätty, unittestit sille tehty ja validointi tehty.
